apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: unico
  namespace: unico-develop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unico
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 85
  - type: Resource
    resource:
      name: memory 
      targetAverageUtilization: 85
