// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/district/{subprefecture}": {
            "get": {
                "description": "Get all the existing District by Subprefecture",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "List existing District by Subprefecture",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subprefecture ID",
                        "name": "subprefecture",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.District"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        },
        "/import-data": {
            "post": {
                "description": "Import CSV Data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Import CSV Data",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File Path",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        },
        "/market": {
            "get": {
                "description": "Get all the existing market",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "List existing market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "zone",
                        "name": "zone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "district",
                        "name": "district",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "neighborhood",
                        "name": "neighborhood",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Market"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Market",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Market",
                "parameters": [
                    {
                        "description": "Create Market",
                        "name": "market",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MarketCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "1": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/entities.Market"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        },
        "/market/:id": {
            "get": {
                "description": "Get all the existing market",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get existing market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market Record",
                        "name": "record",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Market"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        },
        "/market/{id}": {
            "put": {
                "description": "Create a new Market",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market Record",
                        "name": "record",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Market",
                        "name": "market",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MarketUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove Market by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Remove Market",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Market Record",
                        "name": "record",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        },
        "/subprefecture": {
            "get": {
                "description": "Get all the existing Subprefecture",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "List existing Subprefecture",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.SubPrefecture"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.District": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "subPrefectureID": {
                    "type": "integer"
                }
            }
        },
        "entities.Market": {
            "type": "object",
            "properties": {
                "Number": {
                    "type": "string"
                },
                "Street": {
                    "type": "string"
                },
                "area": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "district": {
                    "$ref": "#/definitions/entities.District"
                },
                "districtID": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "record": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "setcents": {
                    "type": "integer"
                },
                "subPrefecture": {
                    "$ref": "#/definitions/entities.SubPrefecture"
                },
                "subPrefectureID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "zone8": {
                    "type": "string"
                }
            }
        },
        "entities.SubPrefecture": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "zone": {
                    "type": "string"
                }
            }
        },
        "models.MarketCreateRequest": {
            "type": "object",
            "required": [
                "area",
                "districtID",
                "latitude",
                "longitude",
                "name",
                "neighborhood",
                "record",
                "reference",
                "setcents",
                "street",
                "subPrefectureID",
                "zone8"
            ],
            "properties": {
                "area": {
                    "type": "integer"
                },
                "districtID": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "record": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "setcents": {
                    "type": "integer"
                },
                "street": {
                    "type": "string"
                },
                "subPrefectureID": {
                    "type": "integer"
                },
                "zone8": {
                    "type": "string"
                }
            }
        },
        "models.MarketUpdateRequest": {
            "type": "object",
            "required": [
                "area",
                "districtID",
                "latitude",
                "longitude",
                "name",
                "neighborhood",
                "reference",
                "setcents",
                "street",
                "subPrefectureID",
                "zone8"
            ],
            "properties": {
                "area": {
                    "type": "integer"
                },
                "districtID": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "setcents": {
                    "type": "integer"
                },
                "street": {
                    "type": "string"
                },
                "subPrefectureID": {
                    "type": "integer"
                },
                "zone8": {
                    "type": "string"
                }
            }
        },
        "rest.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
